dist: xenial
language: python
python:
  - '3.6'

os: linux
linux:
  - '18.04'

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install  -r requirements.txt --use-feature=2020-resolver

before_script:
  - pip3 install -r requirements.txt


services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=tbd_project.settings.travis


script:
  - python3 manage.py test

# safelist
branches:
  only:
    - staging

