arch: amd64 
os: linux
dist: bionic
services:
  - postgresql
  - xvfb
language: python
python:
  - '3.6'
env:
  - DJANGO_SETTINGS_MODULE=tbd_project.settings.travis

addons:
  apt:
    packages:
      - postgresql-server-dev-9.6

install:
  - pip3 install -r requirements.txt


before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3


script:
    - python3 manage.py test


# safelist
branches:
  only:
    - staging

