language: python
python:
  - '3.6'

before_script:
  - pip3 install -r requirements.txt


services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=tbd_project.settings.travis










script:
  - python3 manage.py test

# safelist
branches:
  only:
    - staging

