dist: bionic
services:
  - postgresql
  - xvfb
language: python
python:
  - '3.6'

os: linux


install:
  - pip3 install -r requirements.txt




env: DJANGO_SETTINGS_MODULE=tbd_project.settings.travis



script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - python3 manage.py test


# safelist
branches:
  only:
    - staging

