dist: bionic
services:
  - postgresql
  - xvfb
language: python
python:
  - '3.6'

os: linux
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - pip3 install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


env: DJANGO_SETTINGS_MODULE=tbd_project.settings.travis

script: xvfb-run --server-args="-screen 0 1024x768x24" make test

script:
  - python3 manage.py test

# safelist
branches:
  only:
    - staging

