dist: bionic
language: python
python:
  - '3.6'

os: linux


install:
  - pip3 install -r requirements.txt


services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=tbd_project.settings.travis

addons:
  apt:
    packages:
      firefox-geckodriver

script:
  - python3 manage.py test

# safelist
branches:
  only:
    - staging

