arch: amd64 
os: linux
dist: bionic
services:
  - postgresql
  - xvfb
language: python
python:
  - '3.6'
env:
  - DJANGO_VERSION=3.1
  - DJANGO_SETTINGS_MODULE=tbd_project.settings.travis

install:
  - pip3 install -r requirements.txt


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.28.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3


script:
    - python3 manage.py test


# safelist
branches:
  only:
    - staging

