# Generated by Django 3.1.3 on 2021-01-09 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Calendrier Séances',
            },
        ),
        migrations.CreateModel(
            name='ExchangeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_operational', models.BooleanField()),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor2', to=settings.AUTH_USER_MODEL)),
                ('acceptor_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor2_meeting', to='members.calendarmeeting')),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller2', to=settings.AUTH_USER_MODEL)),
                ('caller_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller2_meeting', to='members.calendarmeeting')),
            ],
            options={
                'verbose_name': 'Echange séance',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('time_slot', models.CharField(max_length=15)),
                ('time', models.FloatField(max_length=2)),
            ],
            options={
                'verbose_name': 'séance',
            },
        ),
        migrations.CreateModel(
            name='ListExchangeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='date2_meeting1', to='members.calendarmeeting')),
                ('date_meeting2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date2_meeting2', to='members.calendarmeeting')),
                ('date_meeting3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date2_meeting3', to='members.calendarmeeting')),
                ('exchange_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.exchangemeeting')),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.meeting')),
            ],
            options={
                'verbose_name': 'List Echange séance',
            },
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.meeting')),
            ],
            options={
                'verbose_name': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='CalendarCustomuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.calendarmeeting')),
            ],
            options={
                'verbose_name': 'Calendrier Utilisateur',
            },
        ),
    ]
